#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom -f --experimental-backends --config ~/.config/picom/picom.conf &
pgrep -x picom > /dev/null || picom -f --config ~/.config/picom/picom.conf --experimental-backends &
pgrep -x lxsession > /dev/null || lxsession &
pgrep -x conky > /dev/null || conky -c ~/.config/conky/conkyrc

#Polybar
~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr
#feh --bg-fill --randomize ~/Wallpapers/*
~/.fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color "#7bc534"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Insomnia desktop='^8' follow=on
bspc rule -a mpv desktop='^6' follow=on state=fullscreen
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pcmanfm desktop='^7' follow=on
bspc rule -a Google-chrome desktop='^4' follow=on
bspc rule -a Screenkey manage=off
