return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "cpp",
        "css",
        "dart",
        "diff",
        "dockerfile",
        "fish",
        "html",
        "http",
        "javascript",
        "git_config",
        "git_rebase",
        "gitcommit",
        "gitattributes",
        "go",
        "json",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "make",
        "prisma",
        "proto",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "rust",
        "scss",
        "sql",
        "svelte",
        "sxhkdrc",
        "toml",
        "yaml",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },
}
